### ISSUE TITLE
Add note about `/etc/dkim_private.key` permissions

### ISSUE THREAD

**Issue by trustytrojan** [guidocella/personal-email-server-guide#1]
As I followed the guide I was swapping between using `filter-dkimsign` and `filter-rspamd` to see why my DKIM signing wasn't working. When I saw the log under `systemctl status opensmtpd`, I saw that `filter-dkimsign` tried to open `/etc/dkim_private.key` and it failed to do so. I played around with the permissions and found that `chmod 004 /etc/dkim_private.key` did the trick: regardless of the owner, all users need the ability to read the file.

I think you should add a note referencing this in the section starting with:
> You can do DKIM signing with filter-dkimsign or rspamd:

It may help others who encounter the same issue.

**Comment by guidocella** [comment]
Done, I also recommended that it only needs to be readable by `_dkimsign` or `_rspamd` so you can change its owner to that if you want to keep 400 permissions.
