### ISSUE TITLE
`filter-dkimsign` doesn't expect a `user` or `group` argument

### ISSUE THREAD

**Issue by trustytrojan** [guidocella/personal-email-server-guide#2]
After screwing up my first VPS I had to set everything up from scratch again. This time around when trying to get the permissions on `/etc/dkim_private.key` right, I read the manpage of `filter-dkimsign`, and nowhere does it expect a `user` or `group` argument. To confirm my suspicion, I removed the `_dkimsign` user, had `opensmtpd` own the file instead with `400` permissions, and `opensmtpd` started without errors.

In the guide, I suggest removing anything regarding a `_dkimsign` user. The file only needs to be readable by `opensmtpd`, as this is what the `filter-dkimsign` process runs as. This is all on Debian 12, BTW.

![image](https://github.com/user-attachments/assets/488802a0-5d4e-4030-b7e6-02b152df35cf)

**Comment by guidocella** [comment]
Updated, thanks for the report. The example was taken from https://man.openbsd.org/smtpd.conf, it must be outdated.
